### ISSUE TITLE
Can access files, please help

### ISSUE THREAD

**Issue by itshahmir** [TomerGamerTV/Bloxcrusher-1.1.8#1]
version https://git-lfs.github.com/spec/v1
oid sha256:4eb03ac5e032baf58837cc76811cbb2870564c14b834383b0adf36b4595686d7
size 136337408

every file just says this

**Comment by TomerGamerTV** [comment]
wdym every files says this what are you talking about

**Comment by itshahmir** [comment]
Every file i open, just has a git version link, a oid and a key which i guess is SHA256, i think its because of the problem: the files size of the repo exceeded 100 mb, thus arent accessible, can you do me a favour and send me the files on my email, please.

Shahmirkhanutmanzai@gmail.com

**Comment by stepper77** [comment]
me too, slide me them at skem@horsefucker.org iydm

**Comment by TomerGamerTV** [comment]
When I will be able to use my pc I will upload the link to this repo so keep an eye on it

**Comment by ghost** [comment]
> Every file i open, just has a git version link, a oid and a key which i guess is SHA256, i think its because of the problem: the files size of the repo exceeded 100 mb, thus arent accessible, can you do me a favour and send me the files on my email, please.
> 
> [Shahmirkhanutmanzai@gmail.com](mailto:Shahmirkhanutmanzai@gmail.com)

You still got the file?

**Comment by ghost** [comment]
> me too, slide me them at [skem@horsefucker.org](mailto:skem@horsefucker.org) iydm

You still got the file?
