### ISSUE TITLE
help

### ISSUE THREAD

**Issue by azazoz09paulpoop** [TomerGamerTV/Bloxcrusher-1.1.8#2]
I'm not seeing any detected hardware on bloxcrusher

**Comment by TomerGamerTV** [comment]
> I'm not seeing any detected hardware on bloxcrusher

1. I'm not the developer of bloxcursher and I can't fix it
2. Bloxcursher officially has been discontinued and will no long work, use something like salad or rbxidle
3. This is just an archive of the program 

If you need help search blox.land on google and join their discord server
