### ISSUE TITLE
Source code inavailable?

### ISSUE THREAD

**Issue by debxylen** [TomerGamerTV/Bloxcrusher-1.1.8#4]
Do you guys plan to release source code? I know its been long but I'm doing something similar. I am trying to learn from source code since I can't solve a problem: tracking rewards. I know we can use unique workers for each device to mine under our organization, but I can't find a RandomX pool which shows rewards earned by each miner separately.

**Comment by debxylen** [comment]
I was trying to make it so that it will just track how long its mining and hashrate, and calculate reward, but the problem is, they might change pool so that they receive mining reward too, and our program still thinks they are mining. I can use minutely checks but its inefficient.

**Comment by TomerGamerTV** [comment]
I'm not the creator of the program so i can't help with that. I just uploaded it here to archive it

**Comment by debxylen** [comment]
I cant find anything related to "bloxcrusher" anywhere, can you link me to
its owner or site or anything related to it

**Comment by TomerGamerTV** [comment]
Search on archive.org. If you can’t find anything I can’t help you

**Comment by debxylen** [comment]
Okay

**Comment by debxylen** [comment]
Thanks
